Добавляет разметку главной страницы
htmlacademy-adaptive/856383-sedona-28 pull request #3
Opened 2023-03-31 21:42 UTC by Mir-Archi

2023-04-02 13:24 UTC, wrgraff requested changes
Я составил [правила ревью](https://telegra.ph/Pravila-revyu-04-02), почитай их перед тем, как приступать к исправлению

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +      <img class="main-header__logo-image" src="/source/img/logo.svg" width="185" height="96" alt="Логотип Sedona">
Неправильный путь к файлу. `source` — это корневая директория, из которой запускается сервер. Соответственно, все пути пишутся именно от директории `source`.

Кроме того, пути должны быть не абсолютные (начинающиеся с `/` это абсолютные пути). С такими путями картинки не всегда и не везде будут работать, например — не будут работать при публикации на Гитхабе.

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +      <button class="main-nav__toggle" type="button"><span class="visually-hidden">Открыть меню</span></button>
Лучше при вкладывании тегов один в другой всегда писать их на разных строках, так читаемость кода заметно проще:
```suggestion
      <button class="main-nav__toggle" type="button">
        <span class="visually-hidden">Открыть меню</span>
      </button>
```

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +      <div class="main-nav__wrapper">
А зачем тут обертка? Есть 100%-ая уверенность, что она нужна?
Лучше заранее оберток не добавлять, если уверенности нет. Убрать потом лишнее сложно и может вызвать много переделок, а добавить обертку по необходимости довольно легко

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +            <a class="site-list__link" href="#">
Страница фото и видео есть — это `catalog.html`

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +    <section class="welcome-block">
Можно не писать "блок":
```suggestion
    <section class="welcome">
```

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +      <img class="welcome-sedona-image" src="#" width="0" height="0" alt="#">
Размеры нужно указать те, которые будут — зачем же писать нули?

Не очень понял почему картинка является блоком `welcome-sedona-image`, а не элементом вышестоящего блока `welcome-block`

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +      <h2 class="description-sedona__title">Седона — небольшой городок в Аризоне,заслуживающий большего!</h2>
```suggestion
      <h2 class="description-sedona__title">Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
```

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +      <h2 class="description-sedona__title">Седона — небольшой городок в Аризоне,заслуживающий большего!</h2>
Текст по смыслу под заголовок подходит плохо

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +            <span class="advantages__number">— №1 —</span>
Эти цифры можно реализовать через декор

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +      <ul class="advantages__list">
А почему не `<ol>`? Список прям пронумерован визуально

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +      <h2 class="interested__title">Заинтересовались?</h2>
Тоже как заголовок не лучшим образом описывает содержание

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +      <button class="search-button" type="button">Найти гостиницу</button>
Почему это кнопка, а не ссылка?

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +      </svg>
Иконка отметки карты в разметке не нужна, карта будет реализована через вставку кода и отметку по макету на ней реализовывать не нужно

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +    <div class="main-footer__wraper">
`wrapper` пишется с двумя `p`

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +      <div class="main-footer__contact contact">
Непонятно зачем в футере столько оберток. И для всех элементов (а чем сам футер не обертка?), и для каждого блока (чем сам список соцсетей не обертка, например?)

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +          <li class="social__item"><a class="social__link social__link--youtube" href="#">Youtube</a></li>
```suggestion
          <li class="social__item">
            <a class="social__link social__link--vkontakte" href="#">Vkontakte</a>
          </li>
          <li class="social__item">
            <a class="social__link social__link--telegram" href="#">Telegram</a>
          </li>
          <li class="social__item">
            <a class="social__link social__link--youtube" href="#">Youtube</a>
          </li>
```

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +          </svg></a>
```suggestion
        <a class="copyright__link" href="#">
          <svg width="27" height="35" viewBox="0 0 27 35" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M13.65 0.449951H13.55L0.0500031 1.84995V26.55L13.55 34.5499L26.95 26.55V1.84995L13.65 0.449951ZM25.05 12.55L13.55 5.74995V5.64995H13.45L13.35 5.54995V5.64995L1.95 12.55V3.54995L13.45 2.34995L25.05 3.54995V12.55ZM13.45 7.24995L24.95 13.95L20.45 16.55L13.35 12.35V13.75L19.25 17.25L18.35 17.75L13.35 14.75V16.15L17.15 18.45L16.35 18.95L13.35 17.15V18.55L15.25 19.65L13.45 20.75L2.05 14.05L13.45 7.24995ZM1.95 15.55L13.35 22.35V23.35L5.45 18.65V20.05L13.45 24.85V25.95L5.45 21.25V22.65L13.45 27.45L21.55 22.55V17.35L24.95 15.35V25.35L13.45 32.25L1.95 25.45V15.55Z" fill="black" />
          </svg>
        </a>
```

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +      <h1 class="visually-hidden">Добро пожаловатьв седону</h1>
```suggestion
      <h1 class="visually-hidden">Добро пожаловать в Седону</h1>
```

2023-04-02 13:24 UTC, wrgraff commented on source/index.html
> +      <img src="#" width="0" height="0" alt="карта">
А класса нет совсем никакого?

2023-04-02 13:24 UTC, wrgraff commented on source/catalog.html
> +          <li class="site-list__item site-list__item--active">
Не главная страница тут активна

2023-04-02 13:24 UTC, wrgraff commented on source/catalog.html
> +          </li>
А где ж ссылки то

2023-04-02 13:24 UTC, wrgraff commented on source/catalog.html
> +    </section>
Это вообще что-то непонятное, почему "седону"?
В целом это выглядит как декоративный элемент, не уверен, что он достоин какого-то контента, тем более — целого `<section>`

2023-04-02 13:24 UTC, wrgraff commented on source/catalog.html
> +      <h2 class="header-foto-video__title">Фото и видео</h2>
Тут должен быть первого уровня заголовок, вполне себе подходит этот видимый текст на роль заголовка всей страницы

2023-04-02 13:24 UTC, wrgraff commented on source/catalog.html
> +    <section class="header-foto-video">
Этот блок одинаковый на внутренних страницах. Это просто заголовок + текст, такие блоки можно называть одинаково и использовать их на разных страницах

2023-04-02 13:24 UTC, wrgraff commented on source/catalog.html
> +      <p class="header-foto-video__text">Не можете решиться на путешествие из-за курса? Фотографии помогут вам забыть о
"Фото" пишется не так, да и в целом два слова не очень удачны для использования.
Можно писать например `media`

```suggestion
      <p class="header-photo-video__text">Не можете решиться на путешествие из-за курса? Фотографии помогут вам забыть о
```

```suggestion
      <p class="header-media__text">Не можете решиться на путешествие из-за курса? Фотографии помогут вам забыть о
```

2023-04-02 13:24 UTC, wrgraff commented on source/catalog.html
> +    <section class="foto">
У секций нужны заголовки собственные

2023-04-02 13:24 UTC, wrgraff commented on source/catalog.html
> +          <div class="foto__wrapper discription-foto">
Надо грамматику английского подкачать бы

```suggestion
          <div class="foto__wrapper description-photo">
```

2023-04-02 13:24 UTC, wrgraff commented on source/catalog.html
> +            <span class="discription-foto__span discription-foto__span--like">1350</span>
А что дает модификатор `discription-foto__span--like`?

2023-04-02 13:24 UTC, wrgraff commented on source/catalog.html
> +            <span class="discription-foto__span discription-foto__span--like">1350</span>
Лучше все-таки писать не `span`. А какой-то "счетчик", "количество", "лайк". Типа так назвать: `description-photo__like`

2023-04-02 13:24 UTC, wrgraff commented on source/catalog.html
> +        <h2 class="video__title">Все ещё сомневаетесь?</h2>
Не дает понимания такой заголовок о том, что здесь видеопрезентация именно. Мы зрячие и видим это, но и незрячим показать это можно сразу же по заголовку

2023-04-02 13:24 UTC, wrgraff commented on source/catalog.html
> +      </div>
Можно использовать более семантичный элемент `<figure>`.
И кнопочку добавить бы, которая сумеет запускать видео (а может кстати и ссылкой ее сделать, чтобы в случае проблем с js был переход на видеохостинг)

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +          <li class="site-list__item site-list__item--active">
Понятно, что меню копируется, но надо же обновлять состояние: поставить ссылки и правильную активную страницу

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +    </section>
Аналогично, чисто декоративный блок зачем-то становится секцией с заголовком первого уровня.
По заголовкам первого уровня обычно можно понять что из себя представляют страницы. Сейчас у тебя получилось, что структура страниц самих по заголовкам:
- Добро пожаловатьв седону
- седону
- Седона

Что по ним можно было бы понять?

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +          </p>
Такие элементы можно делать отдельными переиспользуемыми блоками, так как поля для ввода и другие элементы форм переиспользуются очень активно. И могут быть использованы не только в этой форме, но и в других местах сайта.

Подробнее про это я [сделал плейлист небольших видео](https://youtube.com/playlist?list=PL6xpnt2woRKk0btmfzM2oR6-ste7wZUWm). Оно про БЭМ в целом, но как раз на примеры формы, как одной из самых сложных страниц.

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +            <label class="feedback-form__label" for="visitors-patronymic">ОТЧЕСТВО:</label>
Пишется все в нормальном режиме, строчными буквами с заглавной. Все заглавные делаются через стили

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +        <fieldset class="feedback-form__group">
Блок `feedback-form` получается просто огромным. С ним потом сложно работать будет, если блок такой огромный выходит, то это повод задуматься о том, можно ли его разделить на несколько

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +
Что за тройной пропуск строк?

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +              </label>
Когда есть и элемент и текст, то тоже стоит делать их на разных строках.
Потому что текст где-то в конце строки после закрытия тега сложно замечать

```suggestion
              <label class="control">
                <input class="control-input" type="radio" name="Скорее отрицательное">
                Скорее отрицательное
              </label>
```

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +            <input class="feedback-form__input" type="text" id="visitors-surname" name="visitors-surname" placeholder="Пустота">
Судя по макету "Петр", "Пустота" и "Викторович" это не плейсхолдеры, а заполненные значения

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +                <input class="control-input" type="radio" name="Скорее положительное" checked>Скорее положительное
Атрибут `name` должен быть латиницей указан и совпадать у всех инпутов с `type="radio"`.
Выбор таких инпутов переключается между вариантами с одинаковым `name`. Сейчас ты создал ситуацию, при которой выбираться будет каждый инпут отдельно и отменить этот выбор будет нельзя.

Значение же выбранное передается через атрибут `value`.

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +              </label>
Тут тоже надо латиницей указывать `name`.
В `type="checkbox"` можно указывать его и разным и одинаковым. Если одинаковым, тоже нужно обязательно указывать `value`. Значения в данных формы запишутся в один пункт и отправятся как массив.
А если по отдельности, то придут отдельно

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +              </label>
А почему не `control__input`? Зачем отдельный блок?

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +</section>
Ну не за `<body>` же они должны быть

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +</section>
```suggestion
<section class="feedback-sent">
  <h2 class="feedback-sent__title">Ваш отзыв отправлен</h2>
  <p class="feedback-sent__text">Спасибо за ваше участие, ваш отзыв уже поступил к нам.В ближайшее время мы опубликуем его на
    сайте</p>
</section>
```

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +</section>
Два модальных окна странно делать разными блоками, большая часть стилей будет повторяться же

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +<section class="feedback-sent">
А где кнопки в этих модалках?

2023-04-02 13:24 UTC, wrgraff commented on source/form.html
> +        <button class="button-form" type="submit">Отправить отзыв</button>
Было бы неплохо выделить отдельный блок для разметки кнопок.
Зачем нам каждую кнопку стилизовать отдельно, если они одинаковы на 80%?

2023-04-02 16:03 UTC, Mir-Archi commented on source/index.html
> +      <h2 class="description-sedona__title">Седона — небольшой городок в Аризоне,заслуживающий большего!</h2>
В плане что за место <h2> больше подходит тег <b> или <strong>?
Или имя класса title не подходит?

2023-04-02 16:13 UTC, Mir-Archi commented on source/index.html
> +      <h2 class="description-sedona__title">Седона — небольшой городок в Аризоне,заслуживающий большего!</h2>
В плане что тег "h1" лучше заменить на "b" или "strong"?
Или то что в названии класса title написан?

2023-04-02 16:14 UTC, Mir-Archi commented on source/index.html
> +            <span class="advantages__number">— №1 —</span>
Ну в дизайне же текстом сделано.
А с помощью графики если то как текст превратить в svg?

2023-04-02 17:40 UTC, Mir-Archi commented on source/catalog.html
> +    <section class="header-foto-video">
А разве не лучше что бы они были независимы так сказать на будущее? Вдруг что то добавится в этот блок на одной из страниц.

2023-04-03 07:43 UTC, wrgraff commented on source/catalog.html
> +    <section class="header-foto-video">
Независимость блока как раз и заключается в том, что он может быть применен на любой странице, в любом месте. В любом контексте и сколько угодно раз.

То, что ты описываешь —  это наоборот постановка блока в зависимость от страницы, от контента который она содержит. У сайта страниц может быть и 20, и 30, и 100. Нельзя же на каждую страницу свои неповторимые блоки создавать.

Кроме того, если добавится — ну и добавить. Блок не обязан выглядеть одинаково везде, у него может быть разный контент, например где-то есть картинка, а где-то нет. Да и вид может быть разный, затем и нужны модификаторы, чтобы использовать один и тот же блок, даже если у него фон разного цвета или еще какие-то незначительные различия

2023-04-03 07:45 UTC, wrgraff commented on source/index.html
> +      <h2 class="description-sedona__title">Седона — небольшой городок в Аризоне,заслуживающий большего!</h2>
Если текст на макете не похож по смыслу на заголовок, то текст можно сделать параграфом, оставив класс для придания вида заголовка, а скрытым добавить более логичный заголовок

2023-04-03 07:46 UTC, wrgraff commented on source/index.html
> +            <span class="advantages__number">— №1 —</span>
Декор не равняется графике в svg.
Есть свойство `content` у псевдоэлементов

2023-04-04 16:10 UTC, wrgraff requested changes

2023-04-04 16:10 UTC, wrgraff commented on source/index.html
> +      <img class="main-header__logo-image" src="../source/img/logo.svg" width="185" height="96" alt="Логотип Sedona">
Путь стал относительным, но так тоже не верно. Теперь мы выходим из текущей директории и заходим в `source`.
Директории `source` для сервера не существует. Ее в адресе быть не должно, от нее нужно считать относительный адрес как от корневой.

2023-04-04 16:10 UTC, wrgraff commented on source/index.html
> +      <img class="welcome__sedona-image" src="#" width="282" height="214" alt="#">
Сейчас нейминг местами бывает избыточен. Например, здесь у нас блок `welcome` и в нем одна картинка.

Вполне достаточно указать `welcome__image`, это достаточно специфичный класс: единственная картинка и понятно, в каком она блоке.
Кроме того, есть подозрение, что класс `welcome__sedona-image` связан с тем, что в тексте на картинке написано "Седона". Желательно лишний раз не привязываться к содержимому

2023-04-04 16:10 UTC, wrgraff commented on source/index.html
> +      <p class="introduction__text">Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон!</p>
Да, так сильно лучше уже

2023-04-04 16:10 UTC, wrgraff commented on source/index.html
> +      <a class="search-button button" href="#">Найти гостиницу</a>
Будет логично смиксовать общий БЭМ-блок `button` не с другим блоком, а с элементом родительского блока, примерно так:
```suggestion
      <a class="interested__button button" href="#">Найти гостиницу</a>
```

2023-04-04 16:10 UTC, wrgraff commented on source/index.html
> +      <img class="map__image" src="#" width="320" height="350" alt="Карта">
Хороший поинт когда нет рядом текста с адресом для изображения карты указать этот адрес в `alt`

2023-04-04 16:10 UTC, wrgraff commented on source/catalog.html
> +    </div>
Я бы вообще в разметке не делал его, а сделал бы частью декора. Например, блока `introduction` внутренних страниц (но это потом можно еще подумать)

2023-04-04 16:10 UTC, wrgraff commented on source/index.html
> +      <img class="welcome__sedona-image" src="#" width="282" height="214" alt="#">
А почему `alt` решетка?
Вообще, прямо на этой картинке есть текст же. Хорошей идеей будет ровно этот текст написать в `alt`, ведь в нем суть картинки и есть

2023-04-04 16:10 UTC, wrgraff commented on source/catalog.html
> +        <h3 class="video__title">Все ещё сомневаетесь?</h3>
Так а зачем он нам в роли заголовка? Это ж просто текст по смыслу, он не озаглавливает, он же не дает понимание о содержании
```suggestion
        <p class="video__title">Все ещё сомневаетесь?</p>
```

2023-04-04 16:10 UTC, wrgraff commented on source/catalog.html
> +        <a href="#"></a>
А содержимое? Мы разве не можем поместить туда скрытый текст вроде "смотреть видео"?

2023-04-04 16:10 UTC, wrgraff commented on source/form.html
> +                <input class="checkbox-input" type="checkbox" name="devil's-bridge" checked>
Как и в именах классов, в атрибутах (и в `name` и даже в `value`) не должно быть такой пунктуации.
Стоит писать как и везде только строчными латинскими буквами и используя символы `-` и `_`

2023-04-04 16:10 UTC, wrgraff commented on source/form.html
> +      сайте
Что тут такое происходит с форматированием текста такое загадочное...

2023-04-04 16:10 UTC, wrgraff commented on source/form.html
> +                <input class="radio-input" type="radio" name="overall-impression" value="Rather-positive" checked>
Почему-то лишний БЭМ-блок создается, достаточно и элемента

```suggestion
                <input class="radio__input" type="radio" name="overall-impression" value="Rather-positive" checked>
```

2023-04-04 16:10 UTC, wrgraff commented on source/form.html
> +                <input class="checkbox-input" type="checkbox" name="The-Bell-Mountain" checked>
Аналогично:
```suggestion
                <input class="checkbox__input" type="checkbox" name="The-Bell-Mountain" checked>
```

2023-04-04 16:10 UTC, wrgraff commented on source/form.html
> +            </label>
Забыл кажется тут избавиться от `for` и `id` после вложения инпута в лейбл

2023-04-05 13:35 UTC, wrgraff approved these changes

2023-04-05 13:35 UTC, wrgraff commented on source/catalog.html
>        <img class="main-header__logo-image" src="/source/img/logo.svg" width="185" height="96" alt="Логотип Sedona">
На других страницах нужно тоже поправить пути

2023-04-05 13:35 UTC, wrgraff commented on source/form.html
> +                <input class="radio__input" type="radio" name="overall-impression" value="Rather-positive" checked>
Нет необходимости серверу передавать пунктуацию и лексику:
```suggestion
                <input class="radio__input" type="radio" name="overall-impression" value="positive" checked>
```

2 других можно сделать `negative` и `undefined`

2023-04-05 13:35 UTC, wrgraff commented on source/index.html
> +            Html Academy
Аббревиатура же

```suggestion
            HTML Academy
```

2023-04-05 13:35 UTC, merged